title: vangers-web 
email: caiiiycuk@gmail.com
description: >- 
  Вангеры - одна из легендарных и запоминающихся игр сделанная российскими разработчиками. 
  Эта страничка посвящена веб версии Вангеров. Да-да, теперь в Вангеров можно играть в браузере и не только играть!
baseurl: "" #"vangers-web"
url: "https://caiiiycuk.github.io"
twitter_username: caiiiycuk
github_username:  caiiiycuk

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
