name: SurWeb Linux Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update repos
      run: sudo apt-get update
    - name: install libs
      run: sudo apt-get install cmake libsdl2-dev libsdl2-net-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 ..
    - name: make
      run: make surmap
      working-directory: build
